import { useState } from 'react'
import { ChevronRight, Check, FileWarning } from 'lucide-react'

export function Incident() {
  const [sent, setSent] = useState(false)
  return <>
    <div className="page-header"><div><p className="eyebrow">OPERATIONAL OVERVIEW / S48</p><h1>Incident capture</h1><p className="page-subtitle">Expedition readiness · Antarctic sector / Indian research programme</p></div><div className="header-meta"><span className="label">NEXT REACHABLE RESUPPLY</span><strong className="mono">20 NOV 2027</strong><span className="muted">Window confidence <b className="confidence">82%</b></span></div></div>
    <div className="form-layout"><div className="form-intro"><p className="eyebrow">OPERATIONAL EVENT INTAKE</p><h2>Incident capture</h2><p className="muted">Record an event for operator review. Submission creates a local event draft; it does not sync to a backend.</p><div className="form-note"><FileWarning size={17} /><div><strong>EVENT READY TO COMMIT</strong><span>Review all fields before adding to the operational log.</span></div></div></div><form className="panel incident-form" onSubmit={e => { e.preventDefault(); setSent(true) }}><div className="form-grid"><label>INCIDENT TYPE<select required><option value="">Select type</option><option>Equipment failure</option><option>Weather change</option><option>Personnel</option></select></label><label>STATION<select required><option value="">Select station</option><option>MAITRI</option><option>BHARATI</option><option>FT-3</option></select></label><label>SEVERITY<select required><option value="">Select severity</option><option>INFO</option><option>ATTENTION</option><option>CRITICAL</option></select></label><label>TIME<input required defaultValue="09:15" className="mono" /></label><label className="wide">AFFECTED RESOURCE<input placeholder="e.g. fuel, communications, medical" /></label><label className="wide">DESCRIPTION<textarea required rows={5} placeholder="Describe the observed condition and immediate operational impact..." /></label></div><button className="primary-button" type="submit">{sent ? <><Check size={15} /> EVENT DRAFTED</> : <>REVIEW EVENT <ChevronRight size={15} /></>}</button></form></div>
  </>
}
