import { useState } from 'react'
import { ArrowUpRight, RefreshCw, SlidersHorizontal } from 'lucide-react'

function Badge({ children, tone = 'slate' }: { children: React.ReactNode; tone?: 'red' | 'amber' | 'green' | 'blue' | 'slate' }) { return <span className={`badge badge-${tone}`}>{children}</span> }
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div> }

export function WhatIf() {
  const [scenario, setScenario] = useState('Fuel delivery delayed')
  return <>
    <div className="page-header"><div><p className="eyebrow">OPERATIONAL OVERVIEW / S48</p><h1>What-if simulation</h1><p className="page-subtitle">Expedition readiness · Antarctic sector / Indian research programme</p></div><div className="header-meta"><span className="label">NEXT REACHABLE RESUPPLY</span><strong className="mono">20 NOV 2027</strong><span className="muted">Window confidence <b className="confidence">82%</b></span></div></div>
    <div className="whatif-layout"><div className="whatif-controls panel"><SectionTitle eyebrow="TEMPORARY OVERLAY" title="What-if simulation" /><p className="muted">Apply a temporary event overlay to compare outcomes. The baseline event log remains unchanged.</p><span className="label">SELECT SCENARIO</span>{['Fuel delivery delayed', 'Cargo advanced', 'Inventory recount', 'Personnel moved', 'Consumption reduced'].map(item => <button className={`scenario ${scenario === item ? 'scenario-active' : ''}`} key={item} onClick={() => setScenario(item)}><span className="scenario-radio">{scenario === item && <i />}</span>{item}</button>)}<button className="secondary-button" onClick={() => setScenario('Fuel delivery delayed')}><RefreshCw size={14} /> RESET OVERLAY</button></div><div className="whatif-results"><div className="simulation-banner"><SlidersHorizontal size={16} /><span>SIMULATION ACTIVE</span><b>{scenario}</b><Badge tone="blue">NOT COMMITTED</Badge></div><div className="compare-grid"><div className="panel compare-card"><p className="eyebrow">CURRENT STATE</p><strong>AT RISK</strong><span>8.4 days remaining</span><div className="compare-bar"><i style={{ width: '42%' }} /></div><span className="muted">Decision window · 18 NOV</span></div><ArrowUpRight className="compare-arrow" size={20} /><div className="panel compare-card compare-after"><p className="eyebrow">WHAT-IF STATE</p><strong>CRITICAL</strong><span>5.2 days remaining</span><div className="compare-bar"><i style={{ width: '26%' }} /></div><span className="muted">Decision window · 15 NOV</span></div></div><section className="panel impact-panel"><SectionTitle eyebrow="PROPAGATED EFFECT" title="Operational impact" /><div className="impact-row"><span>Stock margin</span><strong className="red-text">−3.2 days</strong></div><div className="impact-row"><span>Vehicle operations</span><Badge tone="red">CONSTRAINED</Badge></div><div className="impact-row"><span>Required action</span><strong>Review cargo advance</strong></div></section></div></div>
  </>
}
